# Generated by Django 3.2.9 on 2022-02-07 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='interaction_type',
            field=models.CharField(choices=[('EV', 'Event'), ('MT', 'Meeting')], default='EV', max_length=100),
        ),
        migrations.AddField(
            model_name='snippet',
            name='time',
            field=models.TimeField(default='12:00:00'),
        ),
    ]
