# Generated by Django 3.2.9 on 2022-02-07 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0002_auto_20220208_0305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='interaction_type',
            field=models.CharField(choices=[('Event', 'Event'), ('Meeting', 'Meeting')], default='Event', max_length=100),
        ),
    ]
