# Generated by Django 3.2.9 on 2022-01-30 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bread', '0002_auto_20211210_0016'),
    ]

    operations = [
        migrations.DeleteModel(
            name='client',
        ),
        migrations.DeleteModel(
            name='company',
        ),
        migrations.DeleteModel(
            name='employee',
        ),
    ]
